#pragma once
#include "host_device_common.h"

#define BSSRDF_OUTPUT_PLANE 0
#define BSSRDF_OUTPUT_HEMISPHERE 1

#define BSSRDF_RENDER_MODE_FULL_BSSRDF 0
#define BSSRDF_RENDER_MODE_FRESNEL_OUT_ONLY 1
#define BSSRDF_RENDER_MODE_REMOVE_FRESNEL 2
