#pragma once
#include "host_device_common.h"

#define IMPROVED_ENUM_NAME BackgroundType
#define IMPROVED_ENUM_LIST ENUMITEM(CONSTANT_BACKGROUND) ENUMITEM(ENVIRONMENT_MAP) ENUMITEM(SKY_MODEL) 
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME RenderingMethodType
#define IMPROVED_ENUM_LIST ENUMITEM(RECURSIVE_RAY_TRACING) ENUMITEM(AMBIENT_OCCLUSION) ENUMITEM(PATH_TRACING)
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME PinholeCameraType
#define IMPROVED_ENUM_LIST ENUMITEM(INVERSE_CAMERA_MATRIX) ENUMITEM(EYE_LOOKAT_UP_VECTORS) 
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME SamplingMfpType
#define IMPROVED_ENUM_LIST ENUMITEM(X) ENUMITEM(Y) ENUMITEM(Z) ENUMITEM(MEAN) ENUMITEM(MIN) ENUMITEM(MAX)
#include "improved_enum.h"

