#pragma once
#include "host_device_common.h"

#define IMPROVED_ENUM_NAME BackgroundType
#define IMPROVED_ENUM_LIST ENUMITEM_VALUE(CONSTANT_BACKGROUND,0) ENUMITEM_VALUE(ENVIRONMENT_MAP,1) ENUMITEM_VALUE(SKY_MODEL,2) 
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME RenderingMethodType
#define IMPROVED_ENUM_LIST ENUMITEM_VALUE(RECURSIVE_RAY_TRACING,0) ENUMITEM_VALUE(AMBIENT_OCCLUSION,1) ENUMITEM_VALUE(PATH_TRACING,2)
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME PinholeCameraType
#define IMPROVED_ENUM_LIST ENUMITEM_VALUE(INVERSE_CAMERA_MATRIX,0) ENUMITEM_VALUE(EYE_LOOKAT_UP_VECTORS,1) 
#include "improved_enum.h"

#define IMPROVED_ENUM_NAME SamplingMfpType
#define IMPROVED_ENUM_LIST ENUMITEM_VALUE(X,0) ENUMITEM_VALUE(Y,1) ENUMITEM_VALUE(Z,2) ENUMITEM_VALUE(MEAN,3) ENUMITEM_VALUE(MIN,4) ENUMITEM_VALUE(MAX,5)
#include "improved_enum.h"

